name: CI
env:
  SCREENER_API_KEY: secrets.SCREENER_API_KEY
  SAUCE_USERNAME: secrets.SAUCE_USERNAME
  SAUCE_ACCESS_KEY: secrets.SAUCE_ACCESS_KEY
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd my-app
        npm ci
        
    - name: Build app
      run: |
        cd my-app
        npm run build
        
    - name: Execute tests
      run: |
        cd my-app
        npm run test
        
    - name: Start app
      run: |
        cd my-app
        npm start &
        npx wait-on --timeout 60000
